# Mysql, ElasticSearch and Kibana and for Laravel 11.x API testing
services:
  db-test:
    image: mysql:latest
    container_name: mysql-test-cv
    restart: always
    environment:
      MYSQL_DATABASE: laravel-fp-test
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: root
      TZ: "Europe/Paris"
    ports:
      - "3307:3306"
      
  adminer:
    image: adminer
    container_name: adminer-test
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db-test

  minio-cv-test:
    image: 'minio/minio:latest'
    ports:
      - "9001:9001"
      - "8901:8901"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - "./miniotest:/data/minio"
    command: 'minio server /data/minio --console-address ":8901"'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:9000/minio/health/live'
      retries: 3
      timeout: 5s

  app-test:
    image: php:8.2-fpm
    container_name: php-test-cv
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - db-test
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_ENV: testing
    command: >
      sh -c "php artisan config:clear &&
            php artisan cache:clear &&
            php artisan test"
