# Mysql, ElasticSearch and Kibana and for Laravel 11.x API testing
services:
  db-test:
    image: mysql:latest
    container_name: mysql-test-cv
    restart: always
    environment:
      MYSQL_DATABASE: laravel-fp-test
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: root
      TZ: "Europe/Paris"
    ports:
      - "3307:3306"
      
  adminer:
    image: adminer
    container_name: adminer-test
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db-test

  app-test:
    image: php:8.2-fpm
    container_name: php-test-cv
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - db-test
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_ENV: testing
    command: >
      sh -c "php artisan config:clear &&
            php artisan cache:clear &&
            php artisan test"
