# Mysql container

services:
  adminer:
    image: adminer
    container_name: adminer_db
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: db-collect-verithing
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: ${TZ}
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
