name: Laravel CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: docker compose version

      - name: Build and run tests with Docker Compose
        run: |
          docker compose -f docker-compose.testing.yml up --build --abort-on-container-exit --exit-code-from app-test
